services:
  question-service:
    build:
      context: ./QuestionService
      dockerfile: Dockerfile
    container_name: question-service
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/postgres
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    ports:
      - "8081:8080"
    networks:
      - personality-network
  assessment-service:
    build:
      context: ./AssessmentService
      dockerfile: Dockerfile
    container_name: assessment-service
    ports:
      - "8082:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/postgres
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    networks:
      - personality-network
    depends_on:
      - question-service
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - personality-network

networks:
  personality-network:
    driver: bridge

volumes:
  postgres_data: